name: 質問・エラー報告
title: "[質問/エラー] ここに概要を書いてください"
labels: ["question"]
body: |
  ## 1. 実現したいこと

  ## 2. 起きている問題

  ## 3. エラーメッセージがある場合はテキストで
  
  ## 4. 自分で調べたこと/ やったこと

  ## 5. スクリーンショット

  ## 6. 作業しているファイル名

  - [] すべての必要なものを埋めました
  - [] エラーメッセージや実現したいことを最低限ググりました