@startuml 大まかな設計

!define INTERFACE_COLOR #C8E6C9

skinparam linetype ortho

' ============================================
' ブートストラップ
' ============================================
package "Boot Strap" {
    class Program {
        + Main()
    }
}
' ============================================
' アプリケーション
' ============================================

package "Application" {

    class Application {
    }

    interface IApplication INTERFACE_COLOR {
    }

    interface IDebugger INTERFACE_COLOR {
    }




    IApplication <|.. Application
    Application --> IDebugger

}


' ============================================
' エディタ側
' ============================================

package "EditorController" {

    class DebugAdapter {
    }

    class BuiltInGUI {
    }

}

DebugAdapter --> IApplication
BuiltInGUI --> IApplication



' ============================================
' ゲートウェイ
' ============================================

package "Gateways" {

    class SpimAdapter {
    }

}

IDebugger <|.. SpimAdapter

' ============================================
' デバッガ
' ============================================

package "Debugger" {
    ' 独自のデバッガ, TODO
    class PlusPimDebugger {
    }

}

IDebugger <|.. PlusPimDebugger



' ============================================
' 外の依存関係
' ============================================



@enduml
